name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Railway CLI
        run: npm install -g @railway/cli

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build Go binary
        run: go build -o app ./main.go

      - name: Deploy using Railway CLI
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          export RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}
          railway link --project ${{ secrets.PROJECT_ID }}
          railway up --service go-railway-example --detach
