name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Build
        run: go build -o app ./cmd/main.go
      - name: Deploy to Railway
        uses: railwayapp/railway-action@v2
        with:
          serviceName: "go-railway-example"
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
